{
 "title": "Stock prices",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Stock",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"test-bucket\", tag: \"stock\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "52 week high ${Stock}",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: -52w)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\" and r.stock == \"${Stock}\" and r._field == \"close\")\r\n  |> max()\r\n"
    }
   ]
  },
  {
   "title": "52 Week Low ${Stock}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: -52w)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\" and r.stock == \"${Stock}\" and r._field == \"close\")\r\n  |> min()"
    }
   ]
  },
  {
   "title": "Candlesticks ${Stock}",
   "type": "candlestick",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\")\r\n  |> filter(fn: (r) => r.stock == \"${Stock}\")\r\n  |> filter(fn: (r) => r._field == \"open\" or r._field == \"high\" or r._field == \"low\" or r._field == \"close\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"open\", \"high\", \"low\", \"close\"])\r\n"
    }
   ]
  },
  {
   "title": "Close ${Stock}",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\" and r._field == \"close\" and r.stock == \"${Stock}\")\r\n"
    }
   ]
  },
  {
   "title": "Volume ${Stock}",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\" and r.stock == \"${Stock}\" and r._field == \"volume\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Close ${Stock}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock_measurements\" and r[\"stock\"] == \"${Stock}\" and r[\"_field\"] == \"close\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\n  |> yield(name: \"line_chart\")\n"
    }
   ]
  },
  {
   "title": "Comparison Daily Mean Close",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stock_measurements\")\r\n  |> filter(fn: (r) => \r\n     r.stock == \"GOOGL\" or \r\n     r.stock == \"TSLA\" or \r\n     r.stock == \"NFLX\" or \r\n     r.stock == \"MSFT\" or\r\n     r.stock == \"AAPL\" or\r\n     r.stock == \"AMZN\"\r\n  )\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"stock\"], valueColumn: \"_value\")\r\n  |> yield(name: \"daily_mean_close\")\r\n\r\n\r\n"
    }
   ]
  }
 ]
}